substitutions:
  _HUGO_VERSION: "0.79.1"

images: 
  - 'gcr.io/$PROJECT_ID/hugo-${_HUGO_VERSION}:latest'
  
# https://cloud.google.com/cloud-build/docs/build-config

steps:
- id: 'download git code'
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/google/docsy-example.git']

- id: 'download git submodule'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      git config -f .git/config submodule.github_mrraz_techdoc.url https://source.cloud.google.com/silken-inverter-299218/github_mrraz_techdoc 
      git config -f .gitmodules submodule.github_mrraz_techdoc.url https://source.cloud.google.com/silken-inverter-299218/github_mrraz_techdoc
      git submodule init
      git submodule update --init --recursive

- id: 'hugo build site'
  name: 'peaceiris/hugo:latest-full'
  args: ['-s ./']

- id: 'gcloud deploy app'
  name: gcr.io/cloud-builders/gcloud-slim
  dir: deploy/
  args: ['--project=$PROJECT_ID', 'app', 'deploy', 'app.yaml']

options:
  machineType: 'N1_HIGHCPU_32'

timeout: '120s'