substitutions:
  _HUGO_VERSION: "0.79.1"

images: 
  - 'gcr.io/$PROJECT_ID/hugo-${_HUGO_VERSION}:latest'
  
# https://cloud.google.com/cloud-build/docs/build-config

steps:
- id: 'download git code'
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/google/docsy-example.git']

- id: 'download git submodule'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      git config -f .git/config submodule.github_mrraz_techdoc.url https://source.cloud.google.com/silken-inverter-299218/github_mrraz_techdoc 
      git config -f .gitmodules submodule.github_mrraz_techdoc.url https://source.cloud.google.com/silken-inverter-299218/github_mrraz_techdoc
      git submodule init
      git submodule update --init --recursive


# the step needed only only when creating/updating Hugo image
- id: 'budil hugo img'
  name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '--build-arg', 'HUGO_VERSION=${_HUGO_VERSION}',
            '-t', 'gcr.io/$PROJECT_ID/hugo-${_HUGO_VERSION}:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/hugo-${_HUGO_VERSION}:latest',
            '-f', 'deploy/hugo.Dockerfile', 'deploy/'
        ]

- id: 'hugo build site'
  name: 'gcr.io/$PROJECT_ID/hugo-${_HUGO_VERSION}:latest'
  entrypoint: 'sh'
  args:
    - -c
    - |
      pwd
      ls
      hugo - v -s ./
      ls public/

- id: 'gcloud deploy app'
  name: gcr.io/cloud-builders/gcloud-slim
  dir: deploy/
  args: ['--project=$PROJECT_ID', 'app', 'deploy', 'app.yaml']

options:
  machineType: 'N1_HIGHCPU_32'

timeout: '120s'